CREATE TABLE IF NOT EXISTS credenciales.INFORMACIONES (  
    
    -- uuid
    INFORMACIONES_ID VARCHAR(36) DEFAULT ( uuid() ) PRIMARY KEY ,
    
    -- informacion personal
    NAMES VARCHAR( 255 ) NOT NULL ,
    LAST_NAMES VARCHAR( 255 ) NOT NULL ,
    YEARS TINYINT NOT NULL ,
    CELL_PHONO_NUMBER VARCHAR( 12 ) NOT NULL UNIQUE ,
    EMAIL VARCHAR( 255 ) NOT NULL ,

    -- fechas
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	ModificationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ;

