CREATE TABLE IF NOT EXISTS credenciales.IDENTIFICACIONES (  
    
    -- uuid
    IDENTIFICACIONES_ID VARCHAR(36) DEFAULT ( uuid() ) PRIMARY KEY ,
    
    -- fk de la tabla informacion
    INFORMACION VARCHAR(36) NOT NULL ,

    -- fk de la tabla roles
    ROL VARCHAR(36) NOT NULL ,

    -- 
    USUARIO VARCHAR( 255 ) NOT NULL ,
    PASS_WORD VARCHAR( 255 ) NOT NULL ,

    -- fechas
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	ModificationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
    
    -- fk hacia la tabla informaciones
    FOREIGN KEY ( INFORMACION ) REFERENCES INFORMACIONES( INFORMACIONES_ID )
    ON DELETE SET NULL
    ON UPDATE CASCADE
    

    -- fk hacia la tabla roles
    FOREIGN KEY ( ROL ) REFERENCES ROLES( ROLES_ID )
    ON DELETE SET NULL
    ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ;

